wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: huggingface
    huggingface_version: 4.27.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1680528132.331631
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      3:
      - 13
      - 23
      4: 3.8.10
      5: 0.13.10
      6: 4.27.4
      8:
      - 5
